apiVersion: v1
clusters:
- cluster:
    server: https://08B93C5A749C2A630D08762D44CFEC9B.gr7.us-east-2.eks.amazonaws.com

    insecure-skip-tls-verify: true
  name: temporary-cluster
contexts:
- context:
    cluster: temporary-cluster
    user: temporary-user
  name: temporary-context
current-context: temporary-context
users:
- name: temporary-user
  user:
    token: k8s-aws-v1.aHR0cHM6Ly9zdHMudXMtZWFzdC0yLmFtYXpvbmF3cy5jb20vP0FjdGlvbj1HZXRDYWxsZXJJZGVudGl0eSZWZXJzaW9uPTIwMTEtMDYtMTUmWC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVEFWQUFUWVBaVU9DSkpQQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0yJTJGc3RzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTdUMDMzNzU5WiZYLUFtei1FeHBpcmVzPTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCUzQngtazhzLWF3cy1pZCZYLUFtei1TaWduYXR1cmU9NjU1MWI1MWJiNGU2NjRmZjQ1MWIxNGUxNGRlZThhN2Q0MjcxMDViNDAzYzU5MDYzZDAxMzUxMGVkNWY2ZmUyMA
